services:
  submerge:
    build: .
    container_name: submerge
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ./config/config.yaml:/app/config.yaml
    environment:
      - NZL_SUBSCRIBE_URL=${NZL_SUBSCRIBE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.submerge.entrypoints=http"
      - "traefik.http.routers.submerge.rule=Host(`submerge.i.cwllll.com`)"
      - "traefik.http.middlewares.submerge-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.submerge.middlewares=submerge-https-redirect"
      - "traefik.http.routers.submerge-secure.entrypoints=https"
      - "traefik.http.routers.submerge-secure.rule=Host(`submerge.i.cwllll.com`)"
      - "traefik.http.routers.submerge-secure.tls=true"
      - "traefik.http.routers.submerge-secure.service=submerge"
      - "traefik.http.services.submerge.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true

