services:
  teamcity-db:
    image: postgres:latest
    container_name: teamcity-db
    restart: always
    environment:
      - POSTGRES_USER=teamcity_user
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - proxy

  teamcity-server:
    image: jetbrains/teamcity-server:2024.03.3
    container_name: teamcity-server
    restart: unless-stopped
    depends_on:
      - teamcity-db
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - teamcity_server_data:/data/teamcity_server/datadir
      - teamcity_server_logs:/opt/teamcity/logs
    environment:
      - TEAMCITY_HTTPS_PROXY_ENABLED=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teamcity.entrypoints=http"
      - "traefik.http.routers.teamcity.rule=Host(`teamcity.i.cwllll.com`)"
      - "traefik.http.middlewares.teamcity-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.teamcity.middlewares=teamcity-https-redirect"
      - "traefik.http.routers.teamcity-secure.entrypoints=https"
      - "traefik.http.routers.teamcity-secure.rule=Host(`teamcity.i.cwllll.com`)"
      - "traefik.http.routers.teamcity-secure.tls=true"
      - "traefik.http.routers.teamcity-secure.service=teamcity"
      - "traefik.http.services.teamcity.loadbalancer.server.port=8111"
      - "traefik.docker.network=proxy"

  teamcity-agent:
    image: jetbrains/teamcity-agent:2024.03.3
    container_name: teamcity-agent
    networks:
        - proxy
    environment:
      - SERVER_URL=http://teamcity-server:8111

networks:
  proxy:
    external: true

volumes:
  postgres_data:
  teamcity_server_data:
  teamcity_server_logs:

